### ISSUE TITLE
无法获取数据

### ISSUE THREAD

**Issue by JinChengneng** [BennyThink/pyweathercn#1]
```
w = pyweathercn.Weather('北京')
w.data
```
输出为
```
{'code': 500002, 'message': 'Unknown error. Please contact @BennyThink via Telegram.', 'error': "'NoneType' object has no attribute 'index'"}
```

**Comment by BennyThink** [comment]
Thanks for the report, this issue has been fixed in version 1.0.6.

Please update via pip `pip3 install -U pyweathercn`.

If you're using PyPi mirror, please wait until sync finished.
